language: d
d: dmd

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y gcc-multilib

script:
    - dub build --compiler=${DC} --build=release
    - dub test --compiler=${DC} --arch=x86
    - dub test --compiler=${DC} --arch=x86_64 --build=unittest-cov

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        - cromfr@gmail.com